### ISSUE TITLE
Вызов ачивки name -> "name"

### ISSUE THREAD

**Issue by comangamer** [OlegWock/Roselia-achievements#1]
В описании, в строке(строках)
**$ get_achievement(name, trans=achievement_transform)**
нужно **name** заменить на **"name"**, чтобы получилось 
**$ get_achievement("name", trans=achievement_transform)**

Просто отзыв нуба, желающего помочь другим нубам, столкнувшимся с тем же =D

ЗЫ
Спасибо за код - он очень удобен.

**Comment by OlegWock** [comment]
Здесь `name` и `"name"` разные вещи. Первое это переменная, второе -- строка с текстом name. А что вставлять зависит уже от конкретного кейса использования. Эта библиотека пусть и простая, но рассчитана на пользователей хотя бы с минимальными знаниями, которые должны понимать, что строки беруться в кавычки. А лучше благодарностью будет поставить звездочку (правый верхний угол). Спасибо
